/**
 * Unique procedural silhouettes — parts use bone-local space.
 * Legs attach at hips and extend +Y (down) to the floor.
 */

import type { BodyPartDef, FighterVisualProfile } from './types';

function parts(defs: Omit<BodyPartDef, 'z'>[]): BodyPartDef[] {
  return defs.map((d, i) => ({ ...d, z: i }));
}

/** Nyra — slim gunslinger. Legs from hip down to floor (~52px). */
export const NYRA_PROFILE: FighterVisualProfile = {
  id: 'nyra_vex',
  displayName: 'Nyra Vex',
  height: 1.05,
  width: 0.85,
  primary: '#2ee6c5',
  secondary: '#0d9488',
  accent: '#e2e8f0',
  silhouette: 'slim',
  idleSway: 1.1,
  walkBob: 2.4,
  attach: [
    { id: 'r_hand', bone: 'r_forearm', along: 22, perp: 0 },
    { id: 'l_hand', bone: 'l_forearm', along: 22, perp: 0 },
    { id: 'weapon_tip', bone: 'weapon', along: 18, perp: 0 },
    { id: 'weapon_l_tip', bone: 'weapon_l', along: 18, perp: 0 },
    { id: 'chest', bone: 'spine', along: 0, perp: 0 },
    { id: 'feet', bone: 'root', along: 0, perp: 0 },
  ],
  parts: parts([
    {
      id: 'cape',
      bone: 'cape',
      shape: 'poly',
      x: 0,
      y: 0,
      w: 20,
      h: 50,
      color: '#134e4a',
      points: [
        { x: -2, y: 0 },
        { x: 12, y: 4 },
        { x: 16, y: 48 },
        { x: -10, y: 52 },
        { x: -14, y: 18 },
      ],
    },
    // Thighs: from hip bone down toward floor
    { id: 'l_leg', bone: 'l_leg', shape: 'capsule', x: -5, y: 0, w: 12, h: 28, color: '#115e59' },
    { id: 'r_leg', bone: 'r_leg', shape: 'capsule', x: -5, y: 0, w: 12, h: 28, color: '#115e59' },
    // Shin/boot suggestion
    { id: 'l_boot', bone: 'l_leg', shape: 'box', x: -6, y: 26, w: 14, h: 10, color: '#042f2e' },
    { id: 'r_boot', bone: 'r_leg', shape: 'box', x: -6, y: 26, w: 14, h: 10, color: '#042f2e' },
    {
      id: 'torso',
      bone: 'spine',
      shape: 'box',
      x: -12,
      y: -4,
      w: 24,
      h: 36,
      color: '#2ee6c5',
      accent: '#99f6e4',
    },
    { id: 'l_arm', bone: 'l_arm', shape: 'capsule', x: -4, y: 0, w: 9, h: 20, color: '#14b8a6' },
    {
      id: 'l_fore',
      bone: 'l_forearm',
      shape: 'capsule',
      x: -3.5,
      y: 0,
      w: 8,
      h: 18,
      color: '#0f766e',
    },
    { id: 'r_arm', bone: 'r_arm', shape: 'capsule', x: -4, y: 0, w: 9, h: 20, color: '#14b8a6' },
    {
      id: 'r_fore',
      bone: 'r_forearm',
      shape: 'capsule',
      x: -3.5,
      y: 0,
      w: 8,
      h: 18,
      color: '#0f766e',
    },
    {
      id: 'pistol_r',
      bone: 'weapon',
      shape: 'box',
      x: -3,
      y: -2,
      w: 7,
      h: 16,
      color: '#e2e8f0',
      accent: '#2ee6c5',
    },
    {
      id: 'pistol_l',
      bone: 'weapon_l',
      shape: 'box',
      x: -3,
      y: -2,
      w: 7,
      h: 16,
      color: '#e2e8f0',
      accent: '#2ee6c5',
    },
    { id: 'head', bone: 'head', shape: 'ellipse', x: -11, y: -16, w: 22, h: 24, color: '#5eead4' },
    { id: 'visor', bone: 'head', shape: 'box', x: -8, y: -8, w: 16, h: 5, color: '#042f2e' },
  ]),
};

/** Bram — stocky warden. */
export const BRAM_PROFILE: FighterVisualProfile = {
  id: 'bram_kade',
  displayName: 'Bram Kade',
  height: 1.0,
  width: 1.05,
  primary: '#ff4d6d',
  secondary: '#9a3412',
  accent: '#cbd5e1',
  silhouette: 'stocky',
  idleSway: 0.55,
  walkBob: 1.8,
  attach: [
    { id: 'r_hand', bone: 'r_forearm', along: 26, perp: 2 },
    { id: 'l_hand', bone: 'l_forearm', along: 22, perp: 0 },
    { id: 'weapon_tip', bone: 'weapon', along: 26, perp: 0 },
    { id: 'chest', bone: 'spine', along: 0, perp: 0 },
    { id: 'feet', bone: 'root', along: 0, perp: 0 },
  ],
  parts: parts([
    { id: 'l_leg', bone: 'l_leg', shape: 'capsule', x: -7, y: 0, w: 16, h: 26, color: '#7c2d12' },
    { id: 'r_leg', bone: 'r_leg', shape: 'capsule', x: -7, y: 0, w: 16, h: 26, color: '#7c2d12' },
    { id: 'l_boot', bone: 'l_leg', shape: 'box', x: -9, y: 24, w: 20, h: 12, color: '#44403c' },
    { id: 'r_boot', bone: 'r_leg', shape: 'box', x: -9, y: 24, w: 20, h: 12, color: '#44403c' },
    {
      id: 'torso',
      bone: 'spine',
      shape: 'box',
      x: -18,
      y: -6,
      w: 36,
      h: 40,
      color: '#ff4d6d',
      accent: '#fb923c',
    },
    { id: 'pad_l', bone: 'spine', shape: 'box', x: -26, y: -8, w: 12, h: 14, color: '#cbd5e1' },
    { id: 'pad_r', bone: 'spine', shape: 'box', x: 14, y: -8, w: 12, h: 14, color: '#cbd5e1' },
    { id: 'l_arm', bone: 'l_arm', shape: 'capsule', x: -5, y: 0, w: 12, h: 18, color: '#c2410c' },
    {
      id: 'l_fore',
      bone: 'l_forearm',
      shape: 'capsule',
      x: -4.5,
      y: 0,
      w: 11,
      h: 16,
      color: '#9a3412',
    },
    { id: 'r_arm', bone: 'r_arm', shape: 'capsule', x: -6, y: 0, w: 14, h: 18, color: '#c2410c' },
    {
      id: 'gauntlet',
      bone: 'weapon',
      shape: 'box',
      x: -11,
      y: -6,
      w: 26,
      h: 24,
      color: '#e2e8f0',
      accent: '#f97316',
    },
    { id: 'head', bone: 'head', shape: 'ellipse', x: -13, y: -16, w: 26, h: 26, color: '#fda4af' },
    { id: 'helm', bone: 'head', shape: 'box', x: -14, y: -18, w: 28, h: 10, color: '#64748b' },
  ]),
};

/** Iria — tall mage. */
export const IRIA_PROFILE: FighterVisualProfile = {
  id: 'iria_sol',
  displayName: 'Iria Sol',
  height: 1.08,
  width: 0.82,
  primary: '#5ce1ff',
  secondary: '#a78bfa',
  accent: '#f5d76e',
  silhouette: 'tall_mage',
  idleSway: 1.4,
  walkBob: 2.0,
  attach: [
    { id: 'r_hand', bone: 'r_forearm', along: 22, perp: 0 },
    { id: 'l_hand', bone: 'l_forearm', along: 22, perp: 0 },
    { id: 'weapon_tip', bone: 'weapon', along: 42, perp: 0 },
    { id: 'chest', bone: 'spine', along: 0, perp: 0 },
    { id: 'feet', bone: 'root', along: 0, perp: 0 },
  ],
  parts: parts([
    {
      id: 'cloak',
      bone: 'cape',
      shape: 'poly',
      x: 0,
      y: 0,
      w: 30,
      h: 56,
      color: '#1e1b4b',
      points: [
        { x: -8, y: 0 },
        { x: 14, y: 2 },
        { x: 20, y: 50 },
        { x: -14, y: 54 },
        { x: -18, y: 16 },
      ],
    },
    { id: 'l_leg', bone: 'l_leg', shape: 'capsule', x: -4, y: 0, w: 11, h: 30, color: '#312e81' },
    { id: 'r_leg', bone: 'r_leg', shape: 'capsule', x: -4, y: 0, w: 11, h: 30, color: '#312e81' },
    { id: 'l_boot', bone: 'l_leg', shape: 'box', x: -5, y: 28, w: 13, h: 9, color: '#1e1b4b' },
    { id: 'r_boot', bone: 'r_leg', shape: 'box', x: -5, y: 28, w: 13, h: 9, color: '#1e1b4b' },
    {
      id: 'torso',
      bone: 'spine',
      shape: 'box',
      x: -11,
      y: -4,
      w: 22,
      h: 40,
      color: '#5ce1ff',
      accent: '#a78bfa',
    },
    { id: 'l_arm', bone: 'l_arm', shape: 'capsule', x: -3.5, y: 0, w: 8, h: 22, color: '#7dd3fc' },
    {
      id: 'l_fore',
      bone: 'l_forearm',
      shape: 'capsule',
      x: -3,
      y: 0,
      w: 7,
      h: 20,
      color: '#38bdf8',
    },
    { id: 'r_arm', bone: 'r_arm', shape: 'capsule', x: -3.5, y: 0, w: 8, h: 22, color: '#7dd3fc' },
    {
      id: 'r_fore',
      bone: 'r_forearm',
      shape: 'capsule',
      x: -3,
      y: 0,
      w: 7,
      h: 20,
      color: '#38bdf8',
    },
    {
      id: 'staff',
      bone: 'weapon',
      shape: 'box',
      x: -2.5,
      y: -10,
      w: 5,
      h: 54,
      color: '#c4b5fd',
      accent: '#f5d76e',
    },
    {
      id: 'crystal',
      bone: 'weapon',
      shape: 'ellipse',
      x: -7,
      y: -16,
      w: 14,
      h: 14,
      color: '#e879f9',
    },
    {
      id: 'card0',
      bone: 'spine',
      shape: 'box',
      x: 14,
      y: -20,
      w: 10,
      h: 14,
      color: '#e0e7ff',
      accent: '#a78bfa',
    },
    {
      id: 'card1',
      bone: 'spine',
      shape: 'box',
      x: 18,
      y: -4,
      w: 10,
      h: 14,
      color: '#e0e7ff',
      accent: '#5ce1ff',
    },
    { id: 'head', bone: 'head', shape: 'ellipse', x: -10, y: -16, w: 20, h: 24, color: '#e0f2fe' },
    { id: 'crown', bone: 'head', shape: 'box', x: -8, y: -18, w: 16, h: 6, color: '#f5d76e' },
  ]),
};

const BY_ID: Record<string, FighterVisualProfile> = {
  nyra_vex: NYRA_PROFILE,
  bram_kade: BRAM_PROFILE,
  iria_sol: IRIA_PROFILE,
};

export function getVisualProfile(fighterId: string): FighterVisualProfile {
  return (
    BY_ID[fighterId] ?? {
      ...NYRA_PROFILE,
      id: fighterId,
      displayName: fighterId,
      primary: '#94a3b8',
      secondary: '#475569',
    }
  );
}

export const ALL_PROFILES = [NYRA_PROFILE, BRAM_PROFILE, IRIA_PROFILE];
