/**
 * Street Fighter 6–inspired visual profiles.
 * Bold silhouettes, cel palette, exaggerated proportions.
 * Canvas procedural stand-in until glTF LODs land.
 */

import type { BodyPartDef, FighterVisualProfile } from './types';

function parts(defs: Omit<BodyPartDef, 'z'>[]): BodyPartDef[] {
  return defs.map((d, i) => ({ ...d, z: i }));
}

/** Nyra Vex — Rift Gunslinger (Chun-Li agility + gunslinger swagger). */
export const NYRA_PROFILE: FighterVisualProfile = {
  id: 'nyra_vex',
  displayName: 'Nyra Vex',
  title: 'Rift Gunslinger',
  height: 1.12,
  width: 0.92,
  primary: '#4A148C',
  secondary: '#00BCD4',
  accent: '#ECEFF1',
  emission: '#E040FB',
  skin: '#F5C6A8',
  outline: '#1A0A2E',
  silhouette: 'slim',
  idleSway: 1.6,
  walkBob: 2.8,
  exaggeration: 1.7,
  personality: 'cocky',
  attach: [
    { id: 'r_hand', bone: 'r_hand', along: 6, perp: 0 },
    { id: 'l_hand', bone: 'l_hand', along: 6, perp: 0 },
    { id: 'weapon_tip', bone: 'weapon', along: 20, perp: 0 },
    { id: 'weapon_l_tip', bone: 'weapon_l', along: 20, perp: 0 },
    { id: 'chest', bone: 'chest', along: 0, perp: 0 },
    { id: 'feet', bone: 'root', along: 0, perp: 0 },
  ],
  parts: parts([
    // Coat — dramatic silhouette
    {
      id: 'coat',
      bone: 'cape',
      shape: 'poly',
      x: 0,
      y: 0,
      w: 36,
      h: 70,
      color: '#4A148C',
      shade: '#2E0A5C',
      accent: '#7B1FA2',
      rim: '#00BCD4',
      outline: 1.4,
      points: [
        { x: -8, y: -4 },
        { x: 18, y: 0 },
        { x: 28, y: 58 },
        { x: 10, y: 72 },
        { x: -18, y: 68 },
        { x: -24, y: 20 },
      ],
    },
    // Legs — athletic, larger boots
    {
      id: 'l_thigh',
      bone: 'l_leg',
      shape: 'taper',
      x: -7,
      y: 0,
      w: 16,
      h: 26,
      color: '#311B92',
      shade: '#1A0A4A',
      accent: '#00BCD4',
    },
    {
      id: 'r_thigh',
      bone: 'r_leg',
      shape: 'taper',
      x: -7,
      y: 0,
      w: 16,
      h: 26,
      color: '#311B92',
      shade: '#1A0A4A',
      accent: '#00BCD4',
    },
    {
      id: 'l_shin',
      bone: 'l_shin',
      shape: 'capsule',
      x: -5,
      y: 0,
      w: 12,
      h: 24,
      color: '#1A237E',
      shade: '#0D1440',
    },
    {
      id: 'r_shin',
      bone: 'r_shin',
      shape: 'capsule',
      x: -5,
      y: 0,
      w: 12,
      h: 24,
      color: '#1A237E',
      shade: '#0D1440',
    },
    {
      id: 'l_boot',
      bone: 'l_foot',
      shape: 'box',
      x: -10,
      y: -2,
      w: 22,
      h: 12,
      color: '#0D1440',
      accent: '#00BCD4',
      rim: '#E040FB',
      outline: 1.3,
    },
    {
      id: 'r_boot',
      bone: 'r_foot',
      shape: 'box',
      x: -10,
      y: -2,
      w: 22,
      h: 12,
      color: '#0D1440',
      accent: '#00BCD4',
      rim: '#E040FB',
      outline: 1.3,
    },
    // Holsters
    {
      id: 'holster_l',
      bone: 'l_leg',
      shape: 'box',
      x: -4,
      y: 14,
      w: 10,
      h: 14,
      color: '#1A0A2E',
      accent: '#ECEFF1',
    },
    {
      id: 'holster_r',
      bone: 'r_leg',
      shape: 'box',
      x: -4,
      y: 14,
      w: 10,
      h: 14,
      color: '#1A0A2E',
      accent: '#ECEFF1',
    },
    // Torso — fitted suit + tech lines
    {
      id: 'hips',
      bone: 'spine',
      shape: 'box',
      x: -14,
      y: 8,
      w: 28,
      h: 14,
      color: '#4A148C',
      shade: '#2E0A5C',
    },
    {
      id: 'torso',
      bone: 'chest',
      shape: 'taper',
      x: -13,
      y: -4,
      w: 26,
      h: 34,
      color: '#6A1B9A',
      shade: '#4A148C',
      accent: '#00BCD4',
      rim: '#E040FB',
      glow: '#E040FB33',
    },
    // Pauldron (left shoulder only — signature)
    {
      id: 'pauldron',
      bone: 'pauldron',
      shape: 'poly',
      x: 0,
      y: 0,
      w: 20,
      h: 16,
      color: '#ECEFF1',
      shade: '#90A4AE',
      accent: '#00BCD4',
      rim: '#E040FB',
      outline: 1.5,
      points: [
        { x: -10, y: -4 },
        { x: 12, y: -8 },
        { x: 16, y: 6 },
        { x: 4, y: 12 },
        { x: -12, y: 8 },
      ],
    },
    // Arms — defined, tattoo glow
    {
      id: 'l_arm',
      bone: 'l_arm',
      shape: 'capsule',
      x: -5,
      y: 0,
      w: 12,
      h: 20,
      color: '#F5C6A8',
      shade: '#D4A07A',
      accent: '#00BCD4',
      glow: '#00BCD455',
    },
    {
      id: 'l_fore',
      bone: 'l_forearm',
      shape: 'capsule',
      x: -4.5,
      y: 0,
      w: 11,
      h: 18,
      color: '#F5C6A8',
      shade: '#D4A07A',
      glow: '#E040FB44',
    },
    {
      id: 'l_hand',
      bone: 'l_hand',
      shape: 'ellipse',
      x: -7,
      y: -2,
      w: 14,
      h: 12,
      color: '#F5C6A8',
      shade: '#D4A07A',
      outline: 1.2,
    },
    {
      id: 'r_arm',
      bone: 'r_arm',
      shape: 'capsule',
      x: -5,
      y: 0,
      w: 12,
      h: 20,
      color: '#F5C6A8',
      shade: '#D4A07A',
      accent: '#00BCD4',
      glow: '#00BCD455',
    },
    {
      id: 'r_fore',
      bone: 'r_forearm',
      shape: 'capsule',
      x: -4.5,
      y: 0,
      w: 11,
      h: 18,
      color: '#F5C6A8',
      shade: '#D4A07A',
      glow: '#E040FB44',
    },
    {
      id: 'r_hand',
      bone: 'r_hand',
      shape: 'ellipse',
      x: -7,
      y: -2,
      w: 14,
      h: 12,
      color: '#F5C6A8',
      shade: '#D4A07A',
      outline: 1.2,
    },
    // Twin pistols — chunky readable
    {
      id: 'pistol_r',
      bone: 'weapon',
      shape: 'blade',
      x: -4,
      y: -4,
      w: 10,
      h: 22,
      color: '#ECEFF1',
      shade: '#90A4AE',
      accent: '#00BCD4',
      rim: '#E040FB',
      glow: '#E040FB66',
      outline: 1.4,
    },
    {
      id: 'pistol_l',
      bone: 'weapon_l',
      shape: 'blade',
      x: -4,
      y: -4,
      w: 10,
      h: 22,
      color: '#ECEFF1',
      shade: '#90A4AE',
      accent: '#00BCD4',
      rim: '#E040FB',
      glow: '#E040FB66',
      outline: 1.4,
    },
    // Head + ponytail + face
    {
      id: 'hair_back',
      bone: 'hair',
      shape: 'poly',
      x: 0,
      y: 0,
      w: 18,
      h: 40,
      color: '#2E0854',
      shade: '#1A0530',
      accent: '#7B1FA2',
      points: [
        { x: -6, y: -8 },
        { x: 8, y: -4 },
        { x: 12, y: 28 },
        { x: 2, y: 42 },
        { x: -10, y: 30 },
      ],
    },
    {
      id: 'head',
      bone: 'head',
      shape: 'ellipse',
      x: -13,
      y: -18,
      w: 26,
      h: 28,
      color: '#F5C6A8',
      shade: '#D4A07A',
      rim: '#FFE0C2',
      outline: 1.5,
      face: 'base',
    },
    {
      id: 'hair_top',
      bone: 'head',
      shape: 'ellipse',
      x: -14,
      y: -22,
      w: 28,
      h: 14,
      color: '#4A148C',
      shade: '#2E0A5C',
      accent: '#7B1FA2',
    },
    {
      id: 'visor',
      bone: 'head',
      shape: 'box',
      x: -6,
      y: -20,
      w: 14,
      h: 6,
      color: '#00BCD4',
      glow: '#00BCD4AA',
      rim: '#E040FB',
    },
    {
      id: 'eye',
      bone: 'head',
      shape: 'ellipse',
      x: 2,
      y: -8,
      w: 7,
      h: 5,
      color: '#1A0A2E',
      accent: '#00BCD4',
      face: 'eye',
    },
    {
      id: 'brow',
      bone: 'head',
      shape: 'box',
      x: 0,
      y: -12,
      w: 9,
      h: 2.5,
      color: '#2E0A5C',
      face: 'brow',
    },
    {
      id: 'mouth',
      bone: 'head',
      shape: 'box',
      x: 1,
      y: 2,
      w: 8,
      h: 2.5,
      color: '#C2185B',
      face: 'mouth',
    },
  ]),
};

/** Bram Kade — Forge Warden (Zangief mass + armored forge). */
export const BRAM_PROFILE: FighterVisualProfile = {
  id: 'bram_kade',
  displayName: 'Bram Kade',
  title: 'Forge Warden',
  height: 1.18,
  width: 1.22,
  primary: '#E65100',
  secondary: '#616161',
  accent: '#FFD600',
  emission: '#FF6D00',
  skin: '#C47A5A',
  outline: '#1A0A00',
  silhouette: 'stocky',
  idleSway: 0.45,
  walkBob: 1.5,
  exaggeration: 1.9,
  personality: 'stoic',
  attach: [
    { id: 'r_hand', bone: 'r_hand', along: 8, perp: 2 },
    { id: 'l_hand', bone: 'l_hand', along: 8, perp: 0 },
    { id: 'weapon_tip', bone: 'weapon', along: 28, perp: 0 },
    { id: 'chest', bone: 'chest', along: 0, perp: 0 },
    { id: 'feet', bone: 'root', along: 0, perp: 0 },
  ],
  parts: parts([
    // Tattered cape/banner
    {
      id: 'banner',
      bone: 'cape',
      shape: 'poly',
      x: 0,
      y: 0,
      w: 32,
      h: 64,
      color: '#5D4037',
      shade: '#3E2723',
      accent: '#E65100',
      outline: 1.3,
      points: [
        { x: -6, y: -2 },
        { x: 14, y: 2 },
        { x: 22, y: 40 },
        { x: 8, y: 66 },
        { x: -16, y: 58 },
        { x: -20, y: 18 },
      ],
    },
    // Massive legs
    {
      id: 'l_thigh',
      bone: 'l_leg',
      shape: 'taper',
      x: -10,
      y: 0,
      w: 22,
      h: 28,
      color: '#5D4037',
      shade: '#3E2723',
      accent: '#FFD600',
    },
    {
      id: 'r_thigh',
      bone: 'r_leg',
      shape: 'taper',
      x: -10,
      y: 0,
      w: 22,
      h: 28,
      color: '#5D4037',
      shade: '#3E2723',
      accent: '#FFD600',
    },
    {
      id: 'l_shin',
      bone: 'l_shin',
      shape: 'capsule',
      x: -8,
      y: 0,
      w: 18,
      h: 22,
      color: '#616161',
      shade: '#37474F',
      accent: '#FF6D00',
    },
    {
      id: 'r_shin',
      bone: 'r_shin',
      shape: 'capsule',
      x: -8,
      y: 0,
      w: 18,
      h: 22,
      color: '#616161',
      shade: '#37474F',
      accent: '#FF6D00',
    },
    {
      id: 'l_boot',
      bone: 'l_foot',
      shape: 'box',
      x: -14,
      y: -2,
      w: 30,
      h: 14,
      color: '#37474F',
      shade: '#263238',
      accent: '#FFD600',
      outline: 1.5,
    },
    {
      id: 'r_boot',
      bone: 'r_foot',
      shape: 'box',
      x: -14,
      y: -2,
      w: 30,
      h: 14,
      color: '#37474F',
      shade: '#263238',
      accent: '#FFD600',
      outline: 1.5,
    },
    // Bare chest + straps
    {
      id: 'hips',
      bone: 'spine',
      shape: 'box',
      x: -20,
      y: 6,
      w: 40,
      h: 16,
      color: '#5D4037',
      shade: '#3E2723',
    },
    {
      id: 'torso',
      bone: 'chest',
      shape: 'taper',
      x: -22,
      y: -6,
      w: 44,
      h: 42,
      color: '#C47A5A',
      shade: '#8D4E38',
      accent: '#FF6D00',
      rim: '#FFD600',
      glow: '#FF6D0033',
      outline: 1.6,
    },
    {
      id: 'strap',
      bone: 'chest',
      shape: 'box',
      x: -18,
      y: 4,
      w: 36,
      h: 6,
      color: '#3E2723',
      accent: '#FFD600',
    },
    // Huge shoulder pads
    {
      id: 'pad_l',
      bone: 'pauldron',
      shape: 'poly',
      x: 0,
      y: 0,
      w: 24,
      h: 20,
      color: '#9E9E9E',
      shade: '#616161',
      accent: '#FFD600',
      rim: '#FF6D00',
      outline: 1.6,
      points: [
        { x: -14, y: -6 },
        { x: 14, y: -10 },
        { x: 18, y: 8 },
        { x: 0, y: 16 },
        { x: -16, y: 10 },
      ],
    },
    {
      id: 'pad_r',
      bone: 'r_arm',
      shape: 'box',
      x: -8,
      y: -8,
      w: 20,
      h: 14,
      color: '#9E9E9E',
      shade: '#616161',
      accent: '#FFD600',
      outline: 1.4,
    },
    // Arms
    {
      id: 'l_arm',
      bone: 'l_arm',
      shape: 'capsule',
      x: -7,
      y: 0,
      w: 16,
      h: 20,
      color: '#C47A5A',
      shade: '#8D4E38',
      outline: 1.3,
    },
    {
      id: 'l_fore',
      bone: 'l_forearm',
      shape: 'capsule',
      x: -6,
      y: 0,
      w: 15,
      h: 18,
      color: '#C47A5A',
      shade: '#8D4E38',
    },
    {
      id: 'l_hand',
      bone: 'l_hand',
      shape: 'ellipse',
      x: -9,
      y: -2,
      w: 18,
      h: 14,
      color: '#C47A5A',
      shade: '#8D4E38',
      outline: 1.4,
    },
    {
      id: 'r_arm',
      bone: 'r_arm',
      shape: 'capsule',
      x: -8,
      y: 0,
      w: 18,
      h: 20,
      color: '#C47A5A',
      shade: '#8D4E38',
      outline: 1.3,
    },
    // Forge gauntlet — signature
    {
      id: 'gauntlet',
      bone: 'weapon',
      shape: 'poly',
      x: 0,
      y: 0,
      w: 32,
      h: 30,
      color: '#B0BEC5',
      shade: '#607D8B',
      accent: '#FF6D00',
      rim: '#FFD600',
      glow: '#FF6D0099',
      outline: 1.8,
      points: [
        { x: -14, y: -10 },
        { x: 16, y: -12 },
        { x: 20, y: 10 },
        { x: 8, y: 22 },
        { x: -16, y: 18 },
        { x: -18, y: 0 },
      ],
    },
    {
      id: 'r_hand',
      bone: 'r_hand',
      shape: 'ellipse',
      x: -8,
      y: 0,
      w: 16,
      h: 12,
      color: '#90A4AE',
      shade: '#546E7A',
    },
    // Head
    {
      id: 'head',
      bone: 'head',
      shape: 'ellipse',
      x: -15,
      y: -18,
      w: 30,
      h: 30,
      color: '#C47A5A',
      shade: '#8D4E38',
      rim: '#E8A888',
      outline: 1.6,
      face: 'base',
    },
    {
      id: 'helm',
      bone: 'head',
      shape: 'box',
      x: -16,
      y: -22,
      w: 32,
      h: 12,
      color: '#78909C',
      shade: '#455A64',
      accent: '#FFD600',
      outline: 1.4,
    },
    {
      id: 'brow',
      bone: 'head',
      shape: 'box',
      x: -2,
      y: -10,
      w: 14,
      h: 3,
      color: '#3E2723',
      face: 'brow',
    },
    {
      id: 'eye',
      bone: 'head',
      shape: 'ellipse',
      x: 2,
      y: -6,
      w: 6,
      h: 4,
      color: '#FFD600',
      glow: '#FF6D00AA',
      face: 'eye',
    },
    {
      id: 'mouth',
      bone: 'head',
      shape: 'box',
      x: 0,
      y: 4,
      w: 10,
      h: 3,
      color: '#5D4037',
      face: 'mouth',
    },
  ]),
};

/** Iria Sol — Prism Magus (Menat grace + crystal mysticism). */
export const IRIA_PROFILE: FighterVisualProfile = {
  id: 'iria_sol',
  displayName: 'Iria Sol',
  title: 'Prism Magus',
  height: 1.1,
  width: 0.88,
  primary: '#E0F7FA',
  secondary: '#00BCD4',
  accent: '#E040FB',
  emission: '#E040FB',
  skin: '#FFE0D0',
  outline: '#0A1628',
  silhouette: 'tall_mage',
  idleSway: 2.0,
  walkBob: 1.6,
  exaggeration: 1.55,
  personality: 'serene',
  attach: [
    { id: 'r_hand', bone: 'r_hand', along: 6, perp: 0 },
    { id: 'l_hand', bone: 'l_hand', along: 6, perp: 0 },
    { id: 'weapon_tip', bone: 'weapon', along: 48, perp: 0 },
    { id: 'chest', bone: 'chest', along: 0, perp: 0 },
    { id: 'feet', bone: 'root', along: 0, perp: 0 },
  ],
  parts: parts([
    // Flowing robes
    {
      id: 'robe',
      bone: 'cape',
      shape: 'poly',
      x: 0,
      y: 0,
      w: 40,
      h: 72,
      color: '#E0F7FA',
      shade: '#B2EBF2',
      accent: '#00BCD4',
      rim: '#E040FB',
      outline: 1.3,
      points: [
        { x: -12, y: -4 },
        { x: 16, y: 0 },
        { x: 28, y: 50 },
        { x: 6, y: 74 },
        { x: -22, y: 68 },
        { x: -26, y: 16 },
      ],
    },
    {
      id: 'l_thigh',
      bone: 'l_leg',
      shape: 'taper',
      x: -5,
      y: 0,
      w: 13,
      h: 28,
      color: '#B2EBF2',
      shade: '#80DEEA',
    },
    {
      id: 'r_thigh',
      bone: 'r_leg',
      shape: 'taper',
      x: -5,
      y: 0,
      w: 13,
      h: 28,
      color: '#B2EBF2',
      shade: '#80DEEA',
    },
    {
      id: 'l_shin',
      bone: 'l_shin',
      shape: 'capsule',
      x: -4,
      y: 0,
      w: 10,
      h: 24,
      color: '#E0F7FA',
      shade: '#B2EBF2',
    },
    {
      id: 'r_shin',
      bone: 'r_shin',
      shape: 'capsule',
      x: -4,
      y: 0,
      w: 10,
      h: 24,
      color: '#E0F7FA',
      shade: '#B2EBF2',
    },
    {
      id: 'l_foot',
      bone: 'l_foot',
      shape: 'ellipse',
      x: -7,
      y: -2,
      w: 16,
      h: 8,
      color: '#FFE0D0',
      shade: '#E8C4B0',
    },
    {
      id: 'r_foot',
      bone: 'r_foot',
      shape: 'ellipse',
      x: -7,
      y: -2,
      w: 16,
      h: 8,
      color: '#FFE0D0',
      shade: '#E8C4B0',
    },
    {
      id: 'torso',
      bone: 'chest',
      shape: 'taper',
      x: -12,
      y: -4,
      w: 24,
      h: 38,
      color: '#E0F7FA',
      shade: '#B2EBF2',
      accent: '#00BCD4',
      rim: '#E040FB',
      glow: '#E040FB22',
      outline: 1.3,
    },
    // Floating prism orbs (body-space)
    {
      id: 'orb0',
      bone: 'chest',
      shape: 'ellipse',
      x: 18,
      y: -28,
      w: 12,
      h: 12,
      color: '#E040FB',
      accent: '#FFFFFF',
      glow: '#E040FBAA',
      rim: '#00BCD4',
      outline: 1.2,
    },
    {
      id: 'orb1',
      bone: 'chest',
      shape: 'ellipse',
      x: 22,
      y: -6,
      w: 11,
      h: 11,
      color: '#00BCD4',
      accent: '#FFFFFF',
      glow: '#00BCD4AA',
      rim: '#E040FB',
      outline: 1.2,
    },
    {
      id: 'orb2',
      bone: 'chest',
      shape: 'ellipse',
      x: 16,
      y: 14,
      w: 10,
      h: 10,
      color: '#7C4DFF',
      accent: '#FFFFFF',
      glow: '#7C4DFFAA',
      outline: 1.2,
    },
    {
      id: 'l_arm',
      bone: 'l_arm',
      shape: 'capsule',
      x: -4,
      y: 0,
      w: 10,
      h: 22,
      color: '#FFE0D0',
      shade: '#E8C4B0',
      glow: '#00BCD433',
    },
    {
      id: 'l_fore',
      bone: 'l_forearm',
      shape: 'capsule',
      x: -3.5,
      y: 0,
      w: 9,
      h: 20,
      color: '#FFE0D0',
      shade: '#E8C4B0',
    },
    {
      id: 'l_hand',
      bone: 'l_hand',
      shape: 'ellipse',
      x: -6,
      y: -2,
      w: 12,
      h: 11,
      color: '#FFE0D0',
      shade: '#E8C4B0',
    },
    {
      id: 'r_arm',
      bone: 'r_arm',
      shape: 'capsule',
      x: -4,
      y: 0,
      w: 10,
      h: 22,
      color: '#FFE0D0',
      shade: '#E8C4B0',
      glow: '#E040FB33',
    },
    {
      id: 'r_fore',
      bone: 'r_forearm',
      shape: 'capsule',
      x: -3.5,
      y: 0,
      w: 9,
      h: 20,
      color: '#FFE0D0',
      shade: '#E8C4B0',
    },
    {
      id: 'r_hand',
      bone: 'r_hand',
      shape: 'ellipse',
      x: -6,
      y: -2,
      w: 12,
      h: 11,
      color: '#FFE0D0',
      shade: '#E8C4B0',
    },
    // Crystal staff
    {
      id: 'staff',
      bone: 'weapon',
      shape: 'box',
      x: -3,
      y: -14,
      w: 6,
      h: 62,
      color: '#B39DDB',
      shade: '#7E57C2',
      accent: '#FFD54F',
      rim: '#E040FB',
      outline: 1.4,
    },
    {
      id: 'crystal',
      bone: 'weapon',
      shape: 'poly',
      x: 0,
      y: 0,
      w: 18,
      h: 22,
      color: '#E040FB',
      accent: '#FFFFFF',
      glow: '#E040FBCC',
      rim: '#00BCD4',
      outline: 1.5,
      points: [
        { x: 0, y: -18 },
        { x: 10, y: -4 },
        { x: 6, y: 12 },
        { x: -6, y: 12 },
        { x: -10, y: -4 },
      ],
    },
    // Head + headdress
    {
      id: 'hair',
      bone: 'hair',
      shape: 'poly',
      x: 0,
      y: 0,
      w: 22,
      h: 48,
      color: '#E1BEE7',
      shade: '#CE93D8',
      accent: '#E040FB',
      glow: '#E040FB33',
      points: [
        { x: -8, y: -10 },
        { x: 10, y: -6 },
        { x: 14, y: 30 },
        { x: 0, y: 48 },
        { x: -14, y: 28 },
      ],
    },
    {
      id: 'head',
      bone: 'head',
      shape: 'ellipse',
      x: -12,
      y: -18,
      w: 24,
      h: 28,
      color: '#FFE0D0',
      shade: '#E8C4B0',
      rim: '#FFF3E0',
      outline: 1.4,
      face: 'base',
    },
    {
      id: 'headdress',
      bone: 'head',
      shape: 'poly',
      x: 0,
      y: 0,
      w: 20,
      h: 14,
      color: '#FFD54F',
      shade: '#FFA000',
      accent: '#E040FB',
      glow: '#FFD54F66',
      outline: 1.3,
      points: [
        { x: -12, y: -16 },
        { x: 0, y: -24 },
        { x: 12, y: -16 },
        { x: 8, y: -8 },
        { x: -8, y: -8 },
      ],
    },
    {
      id: 'eye',
      bone: 'head',
      shape: 'ellipse',
      x: 1,
      y: -7,
      w: 7,
      h: 5,
      color: '#00BCD4',
      glow: '#E040FBAA',
      face: 'eye',
    },
    {
      id: 'brow',
      bone: 'head',
      shape: 'box',
      x: -1,
      y: -11,
      w: 9,
      h: 2,
      color: '#CE93D8',
      face: 'brow',
    },
    {
      id: 'mouth',
      bone: 'head',
      shape: 'box',
      x: 1,
      y: 3,
      w: 7,
      h: 2,
      color: '#F48FB1',
      face: 'mouth',
    },
  ]),
};

/** Kellan Wisp — Stormblade (Guy/Kim speed + techno-ninja). */
export const KELLAN_PROFILE: FighterVisualProfile = {
  id: 'kellan_wisp',
  displayName: 'Kellan Wisp',
  title: 'Stormblade',
  height: 1.14,
  width: 0.9,
  primary: '#1A237E',
  secondary: '#FFEB3B',
  accent: '#ECEFF1',
  emission: '#00E5FF',
  skin: '#C8A882',
  outline: '#050A1A',
  silhouette: 'wiry',
  idleSway: 1.3,
  walkBob: 3.2,
  exaggeration: 1.75,
  personality: 'intense',
  attach: [
    { id: 'r_hand', bone: 'r_hand', along: 6, perp: 0 },
    { id: 'l_hand', bone: 'l_hand', along: 6, perp: 0 },
    { id: 'weapon_tip', bone: 'weapon', along: 34, perp: 0 },
    { id: 'chest', bone: 'chest', along: 0, perp: 0 },
    { id: 'feet', bone: 'root', along: 0, perp: 0 },
  ],
  parts: parts([
    {
      id: 'cloak',
      bone: 'cape',
      shape: 'poly',
      x: 0,
      y: 0,
      w: 30,
      h: 58,
      color: '#1A237E',
      shade: '#0D1440',
      accent: '#00E5FF',
      rim: '#FFEB3B',
      outline: 1.3,
      points: [
        { x: -6, y: -2 },
        { x: 16, y: 2 },
        { x: 24, y: 42 },
        { x: 4, y: 60 },
        { x: -18, y: 52 },
        { x: -20, y: 14 },
      ],
    },
    {
      id: 'l_thigh',
      bone: 'l_leg',
      shape: 'taper',
      x: -6,
      y: 0,
      w: 14,
      h: 26,
      color: '#283593',
      shade: '#1A237E',
    },
    {
      id: 'r_thigh',
      bone: 'r_leg',
      shape: 'taper',
      x: -6,
      y: 0,
      w: 14,
      h: 26,
      color: '#283593',
      shade: '#1A237E',
    },
    {
      id: 'l_shin',
      bone: 'l_shin',
      shape: 'capsule',
      x: -5,
      y: 0,
      w: 11,
      h: 22,
      color: '#1A237E',
      shade: '#0D1440',
      accent: '#00E5FF',
    },
    {
      id: 'r_shin',
      bone: 'r_shin',
      shape: 'capsule',
      x: -5,
      y: 0,
      w: 11,
      h: 22,
      color: '#1A237E',
      shade: '#0D1440',
      accent: '#00E5FF',
    },
    {
      id: 'l_boot',
      bone: 'l_foot',
      shape: 'box',
      x: -9,
      y: -2,
      w: 20,
      h: 11,
      color: '#0D1440',
      accent: '#FFEB3B',
      glow: '#00E5FF44',
      outline: 1.3,
    },
    {
      id: 'r_boot',
      bone: 'r_foot',
      shape: 'box',
      x: -9,
      y: -2,
      w: 20,
      h: 11,
      color: '#0D1440',
      accent: '#FFEB3B',
      glow: '#00E5FF44',
      outline: 1.3,
    },
    {
      id: 'torso',
      bone: 'chest',
      shape: 'taper',
      x: -13,
      y: -4,
      w: 26,
      h: 36,
      color: '#283593',
      shade: '#1A237E',
      accent: '#00E5FF',
      rim: '#FFEB3B',
      glow: '#00E5FF22',
      outline: 1.4,
    },
    {
      id: 'wrap',
      bone: 'chest',
      shape: 'box',
      x: -10,
      y: 10,
      w: 20,
      h: 5,
      color: '#ECEFF1',
      accent: '#FFEB3B',
    },
    {
      id: 'l_arm',
      bone: 'l_arm',
      shape: 'capsule',
      x: -4.5,
      y: 0,
      w: 11,
      h: 20,
      color: '#C8A882',
      shade: '#A88460',
      glow: '#00E5FF33',
    },
    {
      id: 'l_fore',
      bone: 'l_forearm',
      shape: 'capsule',
      x: -4,
      y: 0,
      w: 10,
      h: 18,
      color: '#C8A882',
      shade: '#A88460',
      accent: '#00E5FF',
    },
    {
      id: 'l_hand',
      bone: 'l_hand',
      shape: 'ellipse',
      x: -6.5,
      y: -2,
      w: 13,
      h: 11,
      color: '#C8A882',
      shade: '#A88460',
      outline: 1.2,
    },
    {
      id: 'r_arm',
      bone: 'r_arm',
      shape: 'capsule',
      x: -4.5,
      y: 0,
      w: 11,
      h: 20,
      color: '#C8A882',
      shade: '#A88460',
      glow: '#00E5FF33',
    },
    {
      id: 'r_fore',
      bone: 'r_forearm',
      shape: 'capsule',
      x: -4,
      y: 0,
      w: 10,
      h: 18,
      color: '#C8A882',
      shade: '#A88460',
      accent: '#FFEB3B',
    },
    {
      id: 'r_hand',
      bone: 'r_hand',
      shape: 'ellipse',
      x: -6.5,
      y: -2,
      w: 13,
      h: 11,
      color: '#C8A882',
      shade: '#A88460',
      outline: 1.2,
    },
    // Energy blade
    {
      id: 'blade',
      bone: 'weapon',
      shape: 'blade',
      x: -3,
      y: -6,
      w: 8,
      h: 44,
      color: '#00E5FF',
      shade: '#00B8D4',
      accent: '#FFEB3B',
      rim: '#FFFFFF',
      glow: '#00E5FFCC',
      outline: 1.6,
    },
    // Hooded head
    {
      id: 'hood',
      bone: 'head',
      shape: 'poly',
      x: 0,
      y: 0,
      w: 28,
      h: 28,
      color: '#1A237E',
      shade: '#0D1440',
      accent: '#00E5FF',
      outline: 1.4,
      points: [
        { x: -14, y: -8 },
        { x: 0, y: -22 },
        { x: 14, y: -8 },
        { x: 12, y: 10 },
        { x: -12, y: 10 },
      ],
    },
    {
      id: 'head',
      bone: 'head',
      shape: 'ellipse',
      x: -11,
      y: -14,
      w: 22,
      h: 24,
      color: '#C8A882',
      shade: '#A88460',
      outline: 1.3,
      face: 'base',
    },
    {
      id: 'eye',
      bone: 'head',
      shape: 'ellipse',
      x: 2,
      y: -6,
      w: 7,
      h: 4,
      color: '#00E5FF',
      glow: '#FFEB3BAA',
      face: 'eye',
    },
    {
      id: 'brow',
      bone: 'head',
      shape: 'box',
      x: 0,
      y: -10,
      w: 9,
      h: 2.5,
      color: '#0D1440',
      face: 'brow',
    },
    {
      id: 'mouth',
      bone: 'head',
      shape: 'box',
      x: 1,
      y: 3,
      w: 6,
      h: 2,
      color: '#5D4037',
      face: 'mouth',
    },
  ]),
};

const BY_ID: Record<string, FighterVisualProfile> = {
  nyra_vex: NYRA_PROFILE,
  bram_kade: BRAM_PROFILE,
  iria_sol: IRIA_PROFILE,
  kellan_wisp: KELLAN_PROFILE,
};

export function getVisualProfile(fighterId: string): FighterVisualProfile {
  return (
    BY_ID[fighterId] ?? {
      ...NYRA_PROFILE,
      id: fighterId,
      displayName: fighterId,
      title: 'Unknown',
    }
  );
}

export const ALL_PROFILES = [NYRA_PROFILE, BRAM_PROFILE, IRIA_PROFILE, KELLAN_PROFILE];
